import os
Import('env')  # Import the environment from SConstruct

# Add include paths
engine_env = env.Clone()
engine_env.Append(
    CPPPATH=['include', 'src'],
    CPPDEFINES=['QEXPORT'],
    # LIBS=['user32']
)
engine_env['LIBS'].extend(['user32'])

# Source files for the library
sources = Glob( 'src/core/*.cc' ) + Glob( 'src/platform/*.cc' )

# Build the library (static or shared)
lib = engine_env.Library(target='engine', source=sources)

# Export the library and include paths for other projects
Export('lib', 'engine_env')