Import('env', 'lib')

testbed_env = env.Clone()
testbed_env.Append(
    CPPPATH=['#testbed/include', '#engine/include'],
    CPPDEFINES=['QIMPORT']
)

sources = Glob('src/*.cc')

target = 'testbed'

executable = testbed_env.Program(target=target, source=sources, LIBS=[lib])
Return('executable')